server:
  port: 8090  # порт для REST API мониторинга

notification:
  socket:
    port: 1111
    bind-address: localhost # слушаем все интерфейсы
    allowed-ip: 91.222.167.188       # Контроллер в локальной сети

logger:
  config: ./logback-spring.xml